### ISSUE TITLE
Forum users cannot login

### ISSUE THREAD

**Issue by karasu** [Antergos/infrastructure#50]
Some users are reporting that they cannot login once they have registered in the forum.

@lots0logs For privacy I've send you two examples by mail and won't put them here.

**Comment by killajoe** [comment]
https://forum.antergos.com/topic/11224/issues-logging-in-the-forum/4

**Comment by manuel-192** [comment]
Yeah, now both my old (manuel) and new (manuel-192, created today) account cannot log in anymore.

**Comment by jchamml** [comment]
Does this affect Arch forums also?  I can't login there anymore either.  It won't send me password reset either.  It won't let me setup a new account with same email either.

**Comment by killajoe** [comment]
> Does this affect Arch forums also? I can't login there anymore either. It won't send me password reset either. It won't let me setup a new account with same email either.

complete different infrastructures ;)

**Comment by karasu** [comment]
It should be solved by now. Please, report it here if it still does not work for you.
